creat branch dev
stepancar-web-programming/2023-fall-lab-portfolio-geraskin-a.-s. pull request #2
Opened 2024-01-12 12:58 UTC by geraskinalekseysergeevich

2024-01-16 07:29 UTC, stepancar commented on src/App.js
> +                        <div className="language-btn__container">
Для защиты, предлагаю воспользоваться css modules

2024-01-16 07:30 UTC, stepancar commented on src/App.js
> +            setLanguage('eng')
что если где-то в приложении уже есть определенная логика добавленная на window.onbeforeunload ?

2024-01-16 07:32 UTC, stepancar commented on src/App.js
> +        setTime(timer)
Давайте подумаем над неймингом time/timer

2024-01-16 07:33 UTC, stepancar commented on src/App.js
> +                    <div className="footer-year">2023</div>
давайте добавим динамики

2024-01-16 07:34 UTC, stepancar commented on src/App.js
> +                    <div className="footer-email">leha.geraskin.80@gmail.com</div>
Давайте добавим возможность открывать стандартным email клиентом

2024-01-16 07:40 UTC, stepancar commented on src/components/DotsBar.jsx
> +                </Dot>)
поскольку, у вас условий наполнения `dots` - более емкой может быть запись вида

```
const dots = Array.from({length: countSlides}, (_, index) => index).map((i) => (
     <Dot
            slideIndex={i}
            func={func}
            currentSlide={currentSlide}
            key={`dot-${i}`}
        />
))
``` 

или еще немного проще

```
const dots = Array.from({length: countSlides}).map((_, i) => (
     <Dot
            slideIndex={i}
            func={func}
            currentSlide={currentSlide}
            key={`dot-${i}`}
        />
))
```

2024-01-16 07:43 UTC, stepancar commented on src/components/Dot.jsx
> +            className={`dot ${slideIndex === currentSlide ? 'dot-active' : ''}`}
Обратите внимание, что с точки зрения ответственности - этот компонент мог бы быть чисто визуальным и принимать на вход только состояние для отображение.
active. Таким образом, если бы вам нужно было бы расширить логику еще одним параметром - вам не пришлось бы изменять компонент.

2024-01-16 13:05 UTC, geraskinalekseysergeevich commented on src/App.js
> +            setLanguage('eng')
если такая логика есть, то этот код бы перезаписал существующий обработчик. 
Допустим, предыдущий это func1, а текущий setLanguage. Для корректной работы в этом месте мы бы запоминали func1, вызывали setLanguage, внутри него вызывали func1 и обратно бы восстанавливали func1. Тогда изначальная логика бы не поменялась, а новый обработчик бы добавился

2024-01-16 13:05 UTC, geraskinalekseysergeevich commented on src/App.js
> +            setLanguage('eng')
если такая логика есть, то этот код бы перезаписал существующий обработчик. 
Допустим, предыдущий это func1, а текущий setLanguage. Для корректной работы в этом месте мы бы запоминали func1, вызывали setLanguage, внутри него вызывали func1 и обратно бы восстанавливали func1. Тогда изначальная логика бы не поменялась, а новый обработчик бы добавился

2024-01-16 13:44 UTC, geraskinalekseysergeevich commented on src/App.js
> +                        <div className="language-btn__container">
надо создать css modules для каждого вынесенного компонента?
у меня проблема, я не могу склонировать репозиторий ни на один свой компьютер. как видите, весь проект в итоге выгрузил одногруппник. я могу только создать файлы через гитхаб, поэтому можете уточнить, насколько сильно нужно разделить css?

2024-01-16 13:53 UTC, geraskinalekseysergeevich commented on src/App.js
> +        setTime(timer)
да, нейминг банальный и по названию не понятно, за что отвечает переменная. изменил на autoMoveSlideTime/Timer/set

2024-01-16 14:08 UTC, geraskinalekseysergeevich commented on src/App.js
> +                    <div className="footer-year">2023</div>
добавил динамику с помощью lazy loading. теперь футер будет загружаться на страницу только когда он может быть виден, что ускорит работу сайта

2024-01-16 14:15 UTC, geraskinalekseysergeevich commented on src/App.js
> +                    <div className="footer-email">leha.geraskin.80@gmail.com</div>
сделал ссылку с mailto. круто, не знал что такое есть

2024-01-16 14:19 UTC, geraskinalekseysergeevich commented on src/components/DotsBar.jsx
> +                </Dot>)
изменил на второй вариант. выглядит понятнее, а работает быстрее или одинаково?

2024-01-16 14:26 UTC, geraskinalekseysergeevich commented on src/components/Dot.jsx
> +            className={`dot ${slideIndex === currentSlide ? 'dot-active' : ''}`}
немного не понимаю, как сделать его визуальным. я знаю, что так слишком сложно и приходится все прокидывать в том числе и функцию, но в этом как раз и проблема, что функция перехода используется еще и для стрелок в другом компоненте, и поскольку это должно работать синхронно, я придумал только вариант прокидывания slideIndex, а за ним и остального, чтобы можно было тут использовать. если бы не было стрелок, то да, это могло выглядеть по другому.

2024-01-16 14:37 UTC, geraskinalekseysergeevich commented on src/App.js
> +                        <div className="language-btn__container">
у меня какие то проблемы с гитом, этот реп не клонируется, не коммитится и постоянно выдает ошибки на всех компьютерах. как видите я даже залить от своего имени не смог проект, его заливал одногруппник Некруз. я меняю все на гитхабе вручную, надеюсь что вам будут видны все изменения

2024-01-16 16:52 UTC, stepancar commented on src/App.js
> +            setLanguage('eng')
или можно воспользоваться addEventListener('beforeonload', () => { ... }), вместо window.onbeforeunload =

2024-01-17 14:47 UTC, geraskinalekseysergeevich commented on src/App.js
> +                        <div className="language-btn__container">
переписал module.css почти ко всем компонентам. не переделал flip card, так как считаю, что это не переиспользуемый компонент, потому что у него разная стилистика в каждом использовании. если бы вы объяснили как это правильно делать, чтобы функционал выносить в компонент как это сделано у меня, и при этом еще стили писать не в общем App.css файле, я был бы очень благодарен

2024-01-17 19:28 UTC, stepancar commented on src/components/Dot.jsx
> +            className={`dot ${slideIndex === currentSlide ? 'dot-active' : ''}`}
Да, решение понятно. 
В таком случае обычно создают Компонент обертку вокруг визуального компонента, задача которого сделать нужный мапинг. Таким образом, ваш визуальный компонент становится чистым, контексто независимым, есть враппер под конкретную задачу, который может быть переиспользован.
Вопрос, нужно ли тогда в данной задаче создавать Чистый компонент и враппер ... Мой ответ нет, конкретно в такой задаче, как вы решаете, часто разработчик не стал бы усложнять и сделал бы как вы.
Однако, давайте в рамках этой дискуссии всетки попрактикуем этот подход

2024-01-18 17:31 UTC, stepancar commented on src/App.js
> +                        <div className="language-btn__container">
@geraskinalekseysergeevich, 
Заметьте, что вы переиспользуете FlipCard. Только при переиспользовании вы пробиваете стили с помощью css каскада чтобы сделать точечные переопределения. 

Как обычно проектируют компонент таким образом чтобы можно было переопределить внешний вид - тем не простая, вариантов множество. 

Один из них - добавить параметры, пропс компоненту например `containerClassName, someButtonClassName` `anythingYouCanOverrideClassName`. Потребитель передает уже имя класса на который будут добавлены стили. и вы уже это делаете когда передаете containerClassName="flipper".

Однако дальше, чтобы определить стиль для него вы используете каскад, хотя можете использовать cssModules. В месте где вам нужно переопределить стили  - передайте className в компонент.

Если ответ не подробный - напишите мне в личку, назначим звонок, я вам помогу разобраться

2024-01-19 00:19 UTC, stepancar commented on src/App.js
> +                                        flexDirection="vertical"
может сделать чтобы открывался нативный диалог для звонка?

2024-01-19 00:22 UTC, stepancar commented on src/components/Footer.jsx
> +                <div>2023</div>
добавим динамики чтобы через год менять не пришлось?

2024-01-19 00:25 UTC, stepancar commented on src/components/SwitchButton.jsx
> +        <label className={classes.language-btn classes.switch}>
Обратите внимание что этот контро не accessible - так как единственный активный элемент тут - input и он скрыт.
Если вы попробуете tabом по навигироваться по странице - навигация игнорирует этот блок.

2024-01-19 00:30 UTC, stepancar commented on src/components/SwitchButton.jsx
> +        <label className={classes.language-btn classes.switch}>
Обратите внимание на то что здесь ошибка. 
В результате сборки 
classes превратится во что-то типа
```
var classes = {'language-btn': 'uniqhashk3242342j34h', switch: 'uniqhashk32dfs42j34h'}
```

а потом вы обращаетесь к classes.language-btn - должна быть ошибка.

2024-01-19 00:35 UTC, stepancar commented on src/components/DotsBar.jsx
> +                </Dot>)
И быстрее и не быстрее)

С одной стороны, знание размера массива может помочь сразу выделить память конкретного размера, расширять массив на каждой итерации не нужно.

С другой стороны, runtime может оптимизировать for.
C третьей стороны, если вообще обрамить все в reduce может быть даже быстрее.

Одно время map, reduce были медленными, что привело к тому, что разработчики стали использовать циклы и пуш прямо в них.

Если суммировать - основной посыл - нужно тестировать.
На размерах до 500 разница будет незаметна.

2024-01-19 14:36 UTC, geraskinalekseysergeevich commented on src/App.js
> +                        <div className="language-btn__container">
я вроде понял. то есть условно я прокидываю пропс для главного контейнера например main_container1, main_container2, а стиль для остальных классов button, h1, p пишу с одинаковыми названиями, просто в css делаю их вложенными к main_container1, 2. 

`.main_container1 {
  .button {}
  .h1 {}
  .p {}
}
`

тогда при рендере в каждом FlipCard будут активны разные стили, так как родительский элемент будет меняться, а в коде все будет выглядеть понятно потому что классы будут одни и те же. спасибо большое, что объяснили, я этим вопросом всю верстку задавался  ))

2024-01-19 15:36 UTC, geraskinalekseysergeevich commented on src/App.js
> +                                        flexDirection="vertical"
немного не понимаю зачем добавлять возможность позвонить с компьютера. если вы имеете в виду открытие окна с поддержкой телефона, то я добавил компонент CallButton, который должен это делать и его можно переиспользовать, если я правильно понял задание

2024-01-19 15:38 UTC, geraskinalekseysergeevich commented on src/components/Footer.jsx
> +                <div>2023</div>
по задумке это год создания сайта )) а текущий год можно показывать с помощью Date().getFullYear()

2024-01-19 15:46 UTC, geraskinalekseysergeevich commented on src/components/SwitchButton.jsx
> +        <label className={classes.language-btn classes.switch}>
он скрыт специально для корректной работы анимации. эту кнопку вообще мне кажется надо полностью переделать, но я первый раз пробовал анимации. для того, чтобы перемещаться табом, можно обернуть label в ссылку <а>, и перекинуть функцию смены языка на нее, но не уверен что это будет корректно работать

2024-01-19 15:57 UTC, geraskinalekseysergeevich commented on src/components/SwitchButton.jsx
> +        <label className={classes.language-btn classes.switch}>
да, точно. исправил на className={'${classes.language-btn} ${classes.switch}'}

2024-01-19 16:27 UTC, geraskinalekseysergeevich commented on src/components/Dot.jsx
> +            className={`dot ${slideIndex === currentSlide ? 'dot-active' : ''}`}
я очень постарался понять, почитать и изменил. что я сделал: изменил компонент Dot, теперь он не принимает никакие пропсы и просто отрисовывает стилизованную точку и наведение на нее. добавил компонент DotWrapper, которые принимает индексы двух слайдов и функцию. внутри себя он отрисовывает div которому присваивает класс dot-active исходя из условий и накидывает на этот div функцию перехода.
по итогу у нас есть переиспользуемый визуальный компонент Dot, который рисует точку, а под другой функционал мы можем создавать другие компоненты Wrapper и выполнять функционал. надеюсь я правильно понял

2024-01-20 02:50 UTC, stepancar commented on src/components/DotWrapper.jsx
> +            className=`${slideIndex === currentSlide ? classes.dot-active : ''}`
@geraskinalekseysergeevich , обратите внимание что тут вам приходится передавать пустую строку или класс, как -то собирать. Бывает такое что вам нужно добавить один класс всегда, а второй по условию. В каком-то и компонентов у вас еще один кейс, где нужно добавить 2 класса и вы пишите что-то типа  `{classname1} ${classname2}`. Чтобы эти не заниматься, случайно не забыть пробелы есть пакет

https://www.npmjs.com/package/classnames

```
import cn from 'classnames'

className={cn({[classes.active]: slideIndex === currentSlide})
```

чтобы сама верстка была еще чище рекомендуется вынести логику

```
const isActive = slideIndex === currentSlide;

className={cn({[classes.active]: isActive })
```

2024-01-20 02:51 UTC, stepancar commented on src/components/DotWrapper.jsx
> +            className=`${slideIndex === currentSlide ? classes.dot-active : ''}`
className=`${slideIndex === currentSlide ? classes.dot-active : ''}` - тут ошибка, идентификатор не может иметь такое имя

2024-01-20 02:51 UTC, stepancar commented on src/components/DotsBar.jsx
> +        return dots
Пожалуйста, пользуйтесь автоматическими форматтерами/ линтерами

2024-01-20 02:52 UTC, stepancar commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
Напоминаю про то что есть некая разница в dependency/ devdependency

2024-01-20 02:57 UTC, stepancar requested changes
Для закрепления важности автоматизации нужно добавить линтеры и github actions. Тогда вы увидите что часть ошибок на которые я указал на самом деле мог вам показать линтер

2024-01-21 00:38 UTC, geraskinalekseysergeevich commented on src/components/DotsBar.jsx
> +        return dots
стараюсь приучить себя, пользуюсь в vs code

2024-01-21 00:49 UTC, geraskinalekseysergeevich commented on src/components/DotWrapper.jsx
> +            className=`${slideIndex === currentSlide ? classes.dot-active : ''}`
забыл фигурные скобки, да. сейчас этого блока нет уже

2024-01-21 00:56 UTC, geraskinalekseysergeevich commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
вынес тесты в dev, также туда можно было вынести линтер

2024-01-21 01:17 UTC, geraskinalekseysergeevich commented
подскажите, пожалуйста. мне линтер выдал ошибку при run на App.js. ругался на функцию moveSlide. я ее переделал, отдельно App.js проверяется зеленым, а когда пытаюсь перезапустить проверку всего проекта та ошибка остается. помогло только пересоздание eslint.yml файла. я что то не понимаю, он только коммиты проверяет или это можно проще сделать без пересоздания?

2024-01-21 19:42 UTC, stepancar commented on src/components/DotsBar.jsx
> +        return dots
@geraskinalekseysergeevich , автоматизация - линтер + форматтер, встроенный в CI - это то, что вам нужно.
Есть еще способ предотвратить коммит если не прошли проверки. для этого используют precommit хуки.
В мире frontend часто используют этот пакет https://www.npmjs.com/package/husky
Это не обязательно делать в этом ПР

2024-01-21 19:43 UTC, stepancar commented on .DS_Store
.DS_Store следует добавить в gitignore

2024-01-21 19:43 UTC, stepancar commented on .github/workflows/eslint.yml
> +        node-version: 14
https://nodejs.org/en/about/previous-releases
Это устаревшая версия node_js

2024-01-21 19:44 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
devDependency

2024-01-21 19:51 UTC, stepancar commented
> подскажите, пожалуйста. мне линтер выдал ошибку при run на App.js. ругался на функцию moveSlide. я ее переделал, отдельно App.js проверяется зеленым, а когда пытаюсь перезапустить проверку всего проекта та ошибка остается. помогло только пересоздание eslint.yml файла. я что то не понимаю, он только коммиты проверяет или это можно проще сделать без пересоздания?

К сожалению, по истории изменений и написанному в этом комментарии не удалось разобраться в ситуации. Судя по конфигам что у вас есть у вас сканируется проект целиком , а не те изменения, которые есть в PR. Что является хоть и решением, которое требует больше времени для выполнения, но при этом работает надежно

2024-01-21 19:57 UTC, stepancar approved these changes
Так как ПР был создан очень поздно, через месяц, относительно дедлайна я вынужден поставить миниимальный балл. С другой стороны, дискуссия в рамках этого ПР меня радует. Вы отвечали на конкретные комментарии, задавали вопросы, уточняли. Считаю что дискуссия удалась.
Поэтому ставлю балл выше несмотря на дедлайн.

Прошу зарезолвить комментарии перед мерджем

2024-01-22 00:03 UTC, geraskinalekseysergeevich commented on .DS_Store
к gitignore в гитхаб нет доступа как я понимаю, удалил файл он все равно не нужен, так как с мака просто загружал проект

2024-01-22 00:04 UTC, geraskinalekseysergeevich commented on .github/workflows/eslint.yml
> +        node-version: 14
изменил на 21.6.0

2024-01-22 00:10 UTC, geraskinalekseysergeevich commented
не знаю сможете ли посмотреть комментарий после мерджа, попробую еще раз объяснить. 
я создал файл eslint.yml, запушил его. при пуше он проверил весь проект и выдал мне ошибку в файле App.js. при пуше изменений самого App.js линтер проверил файл и показал, что все ок. я попробовал перезапустить проверку всего проекта и та ошибка все еще осталась. я подумал, что можно заново создать файл eslint.yml и да, ошибка пропала. вопрос был в том, что можно ли как то проще перезапустить проверку всего проекта, но с внесенными изменениями

2024-01-22 00:13 UTC, geraskinalekseysergeevich commented on package.json
> +    "react-scripts": "5.0.1",
я читал что scripts лучше оставлять в dependency, не верно?

2024-01-22 03:14 UTC, stepancar commented on .DS_Store
Не понял что значит "к gitignore в гитхаб нет доступа "
.gitignore - файл, который лежит в вашем репозитории. При добавлении изменений в коммит командой git add анализирует .gitignore. Файл не добавляется если его путь матчится с правилом .gitignore.

2024-01-22 03:15 UTC, stepancar commented on .github/workflows/eslint.yml
> +        node-version: 14
Обратите внимание, что версия 21.6.0  не является версией LTS, о чем написано на https://nodejs.org/en/about/previous-releases
В продакшене рекомендуется пользоваться версиями LTS

2024-01-22 03:21 UTC, stepancar commented on package.json
> +    "react-scripts": "5.0.1",
@geraskinalekseysergeevich , пришлите где читали. Интересно посмотреть доводы этого автора.
react-scripts - это набор утилит для сборки.

2024-01-22 15:02 UTC, geraskinalekseysergeevich commented on .github/workflows/eslint.yml
> +        node-version: 14
изменил

2024-01-22 15:14 UTC, geraskinalekseysergeevich commented on package.json
> +    "react-scripts": "5.0.1",
https://github.com/facebook/create-react-app/issues/4342

вот тут в статье люди спорят о том, куда лучше выносить сборку. просто как я понял, особого значения для людей это не имеет, это не большая библиотека, а набор скриптов. но для некоторых хостов и прода это может вызвать проблемы при сборке, потому что как я понимаю некоторые сервисы настроены только на установку dependencies, вот.

вы не согласны?

2024-01-22 15:18 UTC, geraskinalekseysergeevich commented on .DS_Store
да, я же писал в начале еще, что сломал этот репозиторий. у меня нет доступа к нему через командную строку, все изменения я делал через сайт github. в .gitignore был добавлен сам .gitignore, поэтому в репозиторий он не залит. соответственно вот такая замкнутая петля))) поэтому я не могу изменить .gitignore без другого какого то компьютера.

2024-01-22 15:19 UTC, geraskinalekseysergeevich commented on package.json
> +    "react-scripts": "5.0.1",
и посмотрите пожалуйста комментарий ниже про eslint.yml, я попытался еще раз объяснить проблему

2024-01-22 15:20 UTC, geraskinalekseysergeevich commented on package.json
> +    "react-scripts": "5.0.1",
и посмотрите пожалуйста комментарий ниже про проблему с линтером, я попробовал еще раз объяснить

2024-03-02 10:59 UTC, merged